apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: lq7hv6jzl-java-springboot
  janus-idp.io/tekton: lq7hv6jzl-java-springboot
  backstage.io/kubernetes-id: lq7hv6jzl-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: lq7hv6jzl-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
